#! /bin/sh

### BEGIN INIT INFO
# Provides:          logstash-shipper
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

. /lib/lsb/init-functions

mode="shipper"
name="logstash-$mode"
logstash_bin="/opt/logstash/bin/logstash"
logstash_conf="/opt/$name.conf"
logstash_log="/data/logs/$name.log"
pid_file="/var/run/$name.pid"

NICE_LEVEL="-n 19"

start () {
	#command="/usr/bin/nice $NICE_LEVEL $logstash_bin agent -f $logstash_conf --log $logstash_log web"
	cmd="/usr/bin/nice"
  cmd_opts="$NICE_LEVEL $logstash_bin agent -f $logstash_conf --log $logstash_log web"
	
  log_daemon_msg "Starting $mode" "$name"
	if start-stop-daemon --start --quiet --oknodo --pidfile "$pid_file" -b -m --exec $cmd -- $cmd_opts; then
		log_end_msg 0
	else
		log_end_msg 1
	fi
}

stop () {
	start-stop-daemon --stop --quiet --oknodo --pidfile "$pid_file"
}

status () {
	status_of_proc -p $pid_file "/usr/bin/java" "$name"
}

case $1 in
	start)
		if status; then exit 0; fi
		start
		;;
	stop)
		stop
		;;
	reload)
		stop
		start
		;;
	restart)
		stop
		start
		;;
	status)
		status && exit 0 || exit $?
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload|status}"
		exit 1
		;;
esac

exit 0
